#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page
# that contains the string Ceci n'est pas une page.
sudo apt-get -y install nginx
sudo service nginx start
echo -e "Ceci n'est pas une page\n" >> /var/www/html/error_404.html
sudo sed -i '/server_name _;$/ a\        error_page 404 /error_404.html;' /etc/nginx/sites-enabled/default
sudo nginx -t
sudo service nginx restart

