#!/usr/bin/env bash
# install nginx web-server
# add a custom header to the http response

sudo apt-get update
sudo apt-get -y install nginx
sudo chown -R 755 /var/www
sudo mv /var/www/html/index.html /var/www/html/index.txt
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/error_404.html
sudo sed -i '/server_name _;$/ a\        error_page 404 /error_404.html;' /etc/nginx/sites-enabled/default
sudo sed -i '/server_name _;/a\\tadd_header X-Served-By $hostname always;' /etc/nginx/sites-enabled/default
sudo service nginx start
