#!/usr/bin/env bash
# Fix port connection
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
sed -i "s/ ipv6only=on//" /etc/nginx/sites-enabled/default
sed -i "s/ ipv6only=on//" /etc/nginx/sites-available/default
service nginx restart
