#!/usr/bin/env bash
# Bash (init) script 101-manage_my_process that manages manage_my_process

pid_file=/var/run/my_process.pid

function start() {
	./manage_my_process &
	echo "$!" > "$pid_file"
}

function stop() {
	read -r bgid < "$pid_file"
	kill "$bgid" &&	rm -f "$pid_file"
}

if [ "$1" == "start" ]
then
	start
	echo "manage_my_process started"
elif [ "$1" == "stop" ]
then
	stop
	echo "manage_my_process stopped"
elif [ "$1" == "restart" ]
then
	stop
	start
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi

