#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd, using the while loop + IFS

file=/etc/passwd

while IFS=: read -r uname pwd uid gid uidinfo hdir cmd line;
do
	echo "The user $uname is part of the $gid gang,"\
	"lives in $hdir and rides $cmd."\
	"$uid's place is protected by the passcode $pwd,"\
	"more info about the user here: $uidinfo"
done < $file

unset IFS
