#!/usr/bin/env bash
# Bash script that displays Best School 10 times.
num=0
while [ "$num" -lt 10 ]
do
	if [ "$num" -eq 3 ]
	then
		echo "bad luck"
	elif [ "$num" -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	num=$(( num + 1 ))
done
