#!/usr/bin/env bash
# change the home IP
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1\tlocalhost/127.0.0.2\tlocalhost/g' ~/hosts.new
echo -e "8.8.8.8\tfacebook.com" >> ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
